name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[build') }}
    steps:
      - name: Checkout Documentation
        uses: actions/checkout@v4
        with:
          path: documentation
      - name: Get latest Expyriment release
        id: latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: expyriment
          repo: expyriment
          excludes: draft#, prerelease
      - name: Checkout Expyriment
        uses: actions/checkout@v4
        with:
          repository: expyriment/expyriment
          path: expyriment
          ref: ${{ steps.latest.outputs.release }}
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
      - name: Build
        run: |
          echo "$PWD"
          cd documentation
          echo "$PWD"
          make html EXPYRIMENT_PATH=../expyriment
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages-test  # change back to gh-pages after testing
          folder: documentation/_build/html/
          target-folder: ./
          clean-exclude: |
            old/
            0.*/
