name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[build]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          python -m pip install sphinx numpydoc sphinx-rtd-theme
      - name: Install expyriment
        run: | # change back to normal install after testing
          # python -m pip install expyriment
          python -m pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple --pre expyriment
      - name: Build
        run: |
          cd sphinx
          make html
          cd ..
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages-test  # change back to gh-pages after testing
          folder: sphinx/html/
          target-folder: ./
          clean-exclude: |
            old/
            0.*/
