name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[build') }}
    steps:
      #- name: Checkout expyriment
      #  run: |
      #    git clone https://github.com/expyriment/expyriment
      #- name: Checkout documentation
      #  run: |
      #    cd expyriment
      #    echo "$PWD"
      #    git clone https://github.com/expyriment/documentation
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: expyriment/expyriment
          path: expyriment
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: documentation
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
      - name: Build
        run: |
          echo "$PWD"
          sudo apt-get install -y tree
          cd
          tree -d
          cd expyriment/documentation/sphinx
          make html
          #python create_rst_api_reference.py
          #sphinx-build -b html _build/html
          cd ..
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages-test  # change back to gh-pages after testing
          folder: sphinx/_build/html/
          target-folder: ./
          clean-exclude: |
            old/
            0.*/
